name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Test Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USERNAME }}
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |
            cd /path/to/deployment/directory
            git pull origin main
            dotnet publish -c Release
            # Autres étapes de déploiement, par exemple, redémarrer le service, etc.
